### ISSUE TITLE
How

### ISSUE THREAD

**Issue by zablik** [perarnborg/vuex-oidc#155] opened 2021-01-14 17:41 UTC
In order to access an API a need to add the current JWT token to API client's default headers.
oidcStore module has an API to get `access_token`, it is `oidcAccessToken` getter.

So my question is how can I call this `oidcAccessToken` getter inside `userLoaded` event callback?
Maybe there is a better place to set this header?
Is there an event to handle access_token change?

Thanks!

```
// In my `store/index.js`

export default createStore({
  state: {},
  mutations: {},
  actions: {},
  modules: {
    oidcStore: vuexOidcCreateStoreModule(
      oidcSettings,
      {
        namespaced: true
      },
      {
        userLoaded(user) {
           // set access_token
          axios.defaults.headers.common['Auth-Token'] = ... ;
        },
        userUnloaded() {
           // delete access_token
           axios.defaults.headers.common['Auth-Token'] = null;
        }
      }
    )
  }
});

**Comment by perarnborg** [comment] 2021-01-14 19:31
Duplicate of #153

**Closed by perarnborg** 2021-01-14 19:31 UTC
